---
title: "ReadMe"
output: html_document
date: "2024-11-27"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Documentation
This is the readme documentation of the this research discontinuity design application on South African data. The data set was retrieved from the NIDS cram survey and the link is attached in the references. The data can be downloaded on the SADRU website that is controlled and monitored by the University of Capetown, South Africa. To replicate this paper, you can source the data from the data folder in the pre-processing file named "intial". We complied it in Stata and we merged household and individual level survey data using pid (person identification number).

The project was completed in the .rmd file "proj_write_up" and the presentation document is the "rdd_foodexpen". The project file should be able to replicate without error as the code is sourced from the code file. As for the presentation, it was completed using the **xaringan** packages so it will only knit in html format and keep its template after installing the package. The script "months" includes all the code used in the project .


Data on google cloud 
https://drive.google.com/file/d/1LpQBM2JteWNGB39gwEbTdGmXY2hk4hjr/view?usp=sharing
